### ISSUE TITLE
Is this mod Dead or abandon

### ISSUE THREAD

**Issue by ModernGamingWorld** [PrinceOfAmber/Storage-Network#501] opened 2023-04-17 18:13 UTC
I like many others have been waiting on fixes for the server-side crash for some time now on 1.19.2 and the Hosting Companies who run servers for our mod packs cant push to our new versions cause this mod is broken.

I did see that the mod developer was active 6 days ago updating some mod called FutureLibrary aka FLIB

**Comment by HalcyonSeas73** [comment] 2023-04-17 20:50
If the mod developer is active and there's already an issue made just be patient, a fix will come when the author has time.

**Comment by HalcyonSeas73** [comment] 2023-04-17 20:51
likely duplicate of #477

**Closed as completed** 2023-06-11 23:05 UTC

**Comment by Lothrazar** [comment] 2023-06-12 13:55
sorry i didnt expect JEI and/or forge to break all my shit again lol
