### ISSUE TITLE
Simple Storage shift click output duplicating items

### ISSUE THREAD

**Issue by Ryzelf** [PrinceOfAmber/Storage-Network#52] opened 2018-02-21 22:16 UTC
Hi Lothrazar.

I have encountered a bug in your mod *simple storage network*.

Whenever you craft with an item which is reusable in the crafting table within the request table it duplicates itself, but only if you shift click the output.

For example, crafting juice from "Pams HarvestCraft" it duplicates the juicer because it is reusable.

I have tried this with other crafting recipes and it does the same such as duplicating buckets while crafting the cake from vanilla minecraft.
(tested with only this one mod installed)

**Comment by arfink** [comment] 2018-02-25 07:32
Can confirm this happens to me too. Version 1.2.2 running in latest Forge as of this writing, which IIRC is 2.2619

**Comment by kreezxil** [comment] 2018-02-25 14:01
Confirmed, it's sad to see this bug is back! I'm also using 1.2.2 and build 2619. We can make a video of it if you need? I swear I reported on this in a prior version but I don't see it to link it.

related: 
https://github.com/PrinceOfAmber/Storage-Network/issues/51

**Comment by PrinceOfAmber** [comment] 2018-02-25 23:57
Fix is on the way! 
![berry fix](https://user-images.githubusercontent.com/621529/36648167-88420222-1a44-11e8-8b18-f800d0de03ab.gif)

**Comment by PrinceOfAmber** [comment] 2018-02-26 02:23
Yep dupe of #51  Check out the fix! https://minecraft.curseforge.com/projects/simple-storage-network/files/2535272

**Closed by PrinceOfAmber** 2018-02-26 02:23 UTC
