### ISSUE TITLE
Crash with jei and storage network

### ISSUE THREAD

**Issue by larskr96** [PrinceOfAmber/Storage-Network#94] opened 2018-08-21 17:22 UTC
it crash when i open any Remote or request table
[crash-2018-08-21_19.11.26-client.txt](https://github.com/PrinceOfAmber/Storage-Network/files/2307344/crash-2018-08-21_19.11.26-client.txt)

Mod versjon=
Storage network 1.2.9
Jei 4.12.0.215

**Comment by PrinceOfAmber** [comment] 2018-08-23 07:02
Yep duplicate of this https://github.com/PrinceOfAmber/Storage-Network/issues/88

Until I get a fix out you have to stay with JEI 212.  

Once i fix my end then it will work with new JEI going forward

**Closed by PrinceOfAmber** 2018-08-23 07:02 UTC
