### ISSUE TITLE
Crash when starting Forge server 1.19.2 - 43.2.0

### ISSUE THREAD

**Issue by Secret-Rabbit** [PrinceOfAmber/Storage-Network#486] opened 2023-02-08 15:18 UTC
Minecraft Version: 1.19.2 

Forge Version: 43.2.0

Mod Version: 1.6.5

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
1. Install the Forge server 1.19.2 - 43.2.0.
2. Install Simple Storage Network.
3. Run the server
4. The server is expected to start. But it crashes.

Log file link:
[console log.txt](https://github.com/Lothrazar/Storage-Network/files/10687064/console.log.txt)

Video/images/gifs (direct upload or link): 
[debug.log](https://github.com/Lothrazar/Storage-Network/files/10687034/debug.log)
[latest.log](https://github.com/Lothrazar/Storage-Network/files/10687036/latest.log)

**Comment by Mrbysco** [comment] 2023-02-08 17:10
Duplicate of #477

**Closed as completed** 2023-02-10 12:31 UTC
