### ISSUE TITLE
Elytra Dupe with Quarks Dragon Scale

### ISSUE THREAD

**Issue by phit** [PrinceOfAmber/Storage-Network#268] opened 2020-04-11 16:01 UTC
Minecraft version & Mod Version: 1.14.4

Quark-r2.0-212.jar
SimpleStorageNetwork-1.14.4-0.2.0.jar

Single player or Server: both

Describe problem (what you were doing / what happened):

https://phit.link/s/2020-04-11_17-53-49.webm

**Comment by Juanan0483** [comment] 2021-12-09 00:19
That is not a bug.
It's a feature of quark
you can check it in the [quark wiki](https://quarkmod.net/#features)
![Opera Instantánea_2021-12-09_011147_quarkmod net](https://user-images.githubusercontent.com/57503614/145311737-e62764a8-0031-4664-8358-d2bb0886256e.png)

**Comment by phit** [comment] 2021-12-09 08:31
did you even watch the video?

**Comment by Lothrazar** [comment] 2022-07-08 15:21
1.14.4 has been retired, issue resolved in 1.16.5+

**Closed as completed by Lothrazar** 2022-07-08 15:21 UTC
Labels: 1.14
