### ISSUE TITLE
[1.12] SSN export cables & RFC filiing cabinets don't play well together

### ISSUE THREAD

**Issue by Spongman** [PrinceOfAmber/Storage-Network#295] opened 2020-07-26 22:37 UTC
cc: @bafomdad
SkyFactory 4
Minecraft version & Mod Version: 1.12.2-1.7.8
real filing cabinet: 1.12-0.2.0.19

Single player or Server: server

Describe problem (what you were doing / what happened):

Storage Export Cable connected to RFC Filing Cabinet containing 8 folders each with >700 items. clicking Export Cable's `Import Filter` button results in:

![image](https://user-images.githubusercontent.com/1088194/88490900-ad014c00-cf53-11ea-9760-a41a129b285b.png)

this is _not_ a rendering issue: hovering over those empty slots _doesn't_ show a popup.

disconnecting/reconnecting the cable doesn't fix it.
breaking the cabinet and replacing it doesn't fix it.
connecting the cable to a different side of the cabinet doesn't fix it.
chaning the order of the folders in the cabinet causes the items in the filter to appear in different locations, but it doesn't change which items are shown.

what's weird, is if i break the cabinet, and then click the `import filter` buton while it's not connected to anything, the same items show up in the filter but without the empty gaps, then after a few ticks they revert back to the same list but with the gaps. again, this is without the cabinet connected to the export cable - the export cable is not connected to anything at this point.

**Comment by Lothrazar** [comment] 2020-11-19 07:56
I just placed a filing cabinet with two folders, a slab and a block. import filter was able to find the items and set it up.  
realfilingcabinet-1.12-0.2.0.20.jar
Also trying to wrap up 1.12 as feature complete since theres so many modpacks using it. marking as works as intended

![295](https://user-images.githubusercontent.com/621529/99637323-87fc8180-29f9-11eb-8b8e-62a4dbbbe3cc.png)

**Closed as completed by Lothrazar** 2020-11-19 07:56 UTC
Labels: compatibility, works as intended, 1.12
